export { default as Categories } from './Categories'
export { default as EditCategory } from './EditCategory'
export { default as EditProduct } from './EditProduct'
export { default as Home } from './Home'
export { default as CreateNew } from './CreateNew'
export { default as Products } from './Products'
